<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 hand.gltf --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'
  import { handColor, handSize} from "$lib/handStore";


  export const ref = new Group()

  const gltf = useGltf('/hand-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations(gltf, ref)
  $: $actions["Arm1"]?.play();
  $: $actions["Lenke1"]?.play();
  $: $actions["Lenke2"]?.play();
  $: $actions["Arm1.301"]?.play();
  

  $: mixer.setTime($handSize);
  $: mixer.timeScale = 0.1;
  
  $: console.log("hei", $handSize)
  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Aloe_product_commercial">
      <T.Mesh
        name="Arm-Light"
        geometry={gltf.nodes[`Arm-Light`].geometry}
        material={gltf.materials[$handColor]}
        position={[-0.06, -0.34, -0.01]}
        rotation={[1.8, 0.6, -0.79]}
        scale={50.21}
      />
      <T.Group
        name="Minutt_viser001"
        position={[0.06, 0.09, 0.09]}
        rotation={[0.15, 0.7, 0.13]}
        scale={[0.12, 0, 0.01]}
      >
        <T.Mesh name="Cube006" geometry={gltf.nodes.Cube006.geometry} material={gltf.materials['Material.013']} />
        <T.Mesh name="Cube006_1" geometry={gltf.nodes.Cube006_1.geometry} material={gltf.materials.Lume} />
      </T.Group>
      <T.Group
        name="Minutt_viser002"
        position={[-0.04, 0.09, 0.1]}
        rotation={[2.95, 0.9, -2.77]}
        scale={[0.08, 0, 0.01]}
      >
        <T.Mesh name="Cube006" geometry={gltf.nodes.Cube006.geometry} material={gltf.materials['Material.013']} />
        <T.Mesh name="Cube006_1" geometry={gltf.nodes.Cube006_1.geometry} material={gltf.materials.Lume} />
      </T.Group>
      <T.Mesh
        name="Kronøs-Logo-white"
        geometry={gltf.nodes['Kronøs-Logo-white'].geometry}
        material={gltf.materials['Kronøs-Logo-white']}
        position={[0.01, 0.1, 0.03]}
        rotation={[0.3, 0, 0]}
        scale={0.05}
      />
      <T.Group name="Nails-Light" position={[-0.06, -0.34, -0.01]} rotation={[1.8, 0.6, -0.79]} scale={50.21}>
        <T.Mesh name="Arm303" geometry={gltf.nodes.Arm303.geometry} material={gltf.materials[`Naill-${$handColor}`]} />
        <T.Mesh name="Arm303_1" geometry={gltf.nodes.Arm303_1.geometry} material={gltf.materials['Nail-Tip']} />
      </T.Group>
      <T.Group
        name="Case_Polsihed"
        position={[0, 0.02, 0.14]}
        rotation={[-2.84, 0.07, -3.14]}
        scale={[-0.27, -0.17, -0.27]}
      >
        <T.Mesh
          name="Cylinder031"
          geometry={gltf.nodes.Cylinder031.geometry}
          material={gltf.materials['Material.029']}
        />
        <T.Mesh
          name="Cylinder031_1"
          geometry={gltf.nodes.Cylinder031_1.geometry}
          material={gltf.materials['Material.030']}
        />
        <T.Mesh
          name="Cylinder031_2"
          geometry={gltf.nodes.Cylinder031_2.geometry}
          material={gltf.materials['Material.046']}
        />
        <T.Group
          name="Armature001"
          position={[0.01, 0.12, -1.16]}
          rotation={[2.31, -0.02, 0.02]}
          scale={[-0.3, -0.38, -0.4]}
        >
          <T is={gltf.nodes.Bone_1} />
          <T.Group name="Lenke001">
            <T.SkinnedMesh
              name="Cube017"
              geometry={gltf.nodes.Cube017.geometry}
              material={gltf.materials['Metal-01']}
              skeleton={gltf.nodes.Cube017.skeleton}
            />
            <T.SkinnedMesh
              name="Cube017_1"
              geometry={gltf.nodes.Cube017_1.geometry}
              material={gltf.materials['Material.045']}
              skeleton={gltf.nodes.Cube017_1.skeleton}
            />
          </T.Group>
        </T.Group>
        <T.Group name="Armature" position={[0, 0.05, 1.22]} rotation={[1.1, -0.01, 3.14]} scale={[-0.3, -0.34, -0.44]}>
          <T is={gltf.nodes.Bone} />
          <T.Group name="Lenke">
            <T.SkinnedMesh
              name="Cube026"
              geometry={gltf.nodes.Cube026.geometry}
              material={gltf.materials['Material.045']}
              skeleton={gltf.nodes.Cube026.skeleton}
            />
            <T.SkinnedMesh
              name="Cube026_1"
              geometry={gltf.nodes.Cube026_1.geometry}
              material={gltf.materials['Metal-01']}
              skeleton={gltf.nodes.Cube026_1.skeleton}
            />
          </T.Group>
        </T.Group>
        <T.Mesh
          name="Caseback"
          geometry={gltf.nodes.Caseback.geometry}
          material={gltf.materials['Material.046']}
          position={[0, 0.05, 0]}
          scale={[0.86, 0.04, 0.86]}
        />
        <T.Mesh
          name="Caseback_Riller"
          geometry={gltf.nodes.Caseback_Riller.geometry}
          material={gltf.materials['Material.046']}
          position={[0, 0.05, 0]}
          scale={[0.86, 0.04, 0.86]}
        />
        <T.Mesh
          name="Caseback002"
          geometry={gltf.nodes.Caseback002.geometry}
          material={gltf.materials['Material.046']}
          position={[0, 0.05, 0]}
          scale={[0.86, 0.04, 0.86]}
        />
        <T.Mesh
          name="Crown003"
          geometry={gltf.nodes.Crown003.geometry}
          material={gltf.materials.Metal}
          position={[1.07, -0.14, 0]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={[0.15, 0.05, 0.09]}
        >
          <T.Mesh
            name="Crown_Mount001"
            geometry={gltf.nodes.Crown_Mount001.geometry}
            material={gltf.nodes.Crown_Mount001.material}
            position={[0, 1.23, 0]}
            scale={[0.15, 0.26, 0.15]}
          />
        </T.Mesh>
        <T.Mesh
          name="Dial001"
          geometry={gltf.nodes.Dial001.geometry}
          material={gltf.materials.Nordlys}
          position={[0, -0.19, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.05, -0.01, -0.05]}
        >
          <T.Group name="12_Markør001" position={[0, 7.34, -13.75]} scale={[0.37, 1.67, 0.97]}>
            <T.Mesh name="Cube004" geometry={gltf.nodes.Cube004.geometry} material={gltf.materials['Material.045']} />
            <T.Mesh name="Cube004_1" geometry={gltf.nodes.Cube004_1.geometry} material={gltf.materials.Lume} />
          </T.Group>
          <T.Mesh
            name="Center_circle003"
            geometry={gltf.nodes.Center_circle003.geometry}
            material={gltf.materials['Material.029']}
            position={[0, 8.06, 0]}
            scale={[-0.04, -0.96, -0.04]}
          />
          <T.Mesh
            name="Center_circle004"
            geometry={gltf.nodes.Center_circle004.geometry}
            material={gltf.materials['Material.013']}
            position={[0, 7.34, 10.61]}
            scale={[-0.01, -0.17, -0.01]}
          />
          <T.Mesh
            name="Center_dot_002"
            geometry={gltf.nodes.Center_dot_002.geometry}
            material={gltf.materials['Material.013']}
            position={[0, 7.34, 10.61]}
            scale={[-0.01, -0.07, -0.01]}
          />
          <T.Mesh
            name="Center_dot002"
            geometry={gltf.nodes.Center_dot002.geometry}
            material={gltf.materials['Material.013']}
            position={[0, 7.34, 0]}
            scale={[-0.01, -0.73, -0.01]}
          />
          <T.Mesh
            name="Circle_markører001"
            geometry={gltf.nodes.Circle_markører001.geometry}
            material={gltf.materials['Material.029']}
            position={[0, 7.34, 1.2]}
            scale={[-0.03, -0.3, -0.03]}
          />
          <T.Mesh
            name="Logo001"
            geometry={gltf.nodes.Logo001.geometry}
            material={gltf.materials['Material.029']}
            position={[0, 7.34, -5.35]}
            scale={[1.06, 12.66, 1.06]}
          />
          <T.Group
            name="Markører001"
            position={[0, 7.34, 0]}
            rotation={[0, -Math.PI / 6, Math.PI]}
            scale={[-0.37, -1.67, -0.97]}
          >
            <T.Mesh name="Cube005" geometry={gltf.nodes.Cube005.geometry} material={gltf.materials['Material.045']} />
            <T.Mesh name="Cube005_1" geometry={gltf.nodes.Cube005_1.geometry} material={gltf.materials.Lume} />
          </T.Group>
          <T.Mesh
            name="Sekund_viser001"
            geometry={gltf.nodes.Sekund_viser001.geometry}
            material={gltf.materials['Material.029']}
            position={[-1.08, 7.34, 10.05]}
            rotation={[-Math.PI, 0.51, -Math.PI]}
            scale={[-1.07, -0.51, -0.06]}
          />
          <T.Mesh
            name="Sub_Dial_Markers002"
            geometry={gltf.nodes.Sub_Dial_Markers002.geometry}
            material={gltf.materials['Material.029']}
            position={[0, 7.34, 10.52]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.13, -4.96, -0.4]}
          />
        </T.Mesh>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
